### ISSUE TITLE
readme doesn't show the footprint or output voltage of u1

### ISSUE THREAD

**Issue by ogg1e** [HenrykRichter/ScsiTerm#2]
It would be nice if the readme had an example part # for u1, or the footprint and characteristics of U1.

**Comment by HenrykRichter** [comment]
The readme did already mention the voltage regulator. A common LD1117 SC-R, LM1117 DTX-ADJ or AMS1117-Adj will have the intended characteristics. I've mounted the first of the list on my prototype PCBs. The typical footprint for those parts is SOT-223.

You could also look out for xx1117-2.85 parts. In that case of the 2.85V fixed regulator, leave R21 open and short either C3 or R20.
